# coding: utf-8

categories = {}
categories.update({'hipoteca':['Transferencia',
                            'dico recibido',
                            'dico emitido',
                            'hipoteca',
                            'Hipoteca',
                            'MATERNIDAD',
                            'prestamo',
                            'Traspaso emitido',
                            'Traspaso recibido',
                            'Traspaso interno'
                            ]})
categories.update({'roba':['PRIVEE',
                    'Showroom',
                    'PRIVALIA',
                    'Privalia',
                    'TUC TUC',
                    'KIABI',
                    'TETATET',
                    'PICCOLLETTI',
                    'MERCERIA',
                    'HAPPY FRIDAY',
                    'VERTBAUDET',
                    'AMICS ESPLUGUES',
                    ]})
categories.update({'amazon':['AMZN',
                            'AMAZON',
                            'Amazon',
                            'amazon']})
categories.update({'a_domicili':['BIOCHEF',
                                        'VIENA',
                                        'PIZZA MARKET',
                                        'ANEL',
                                        'ENOTECA PIRAS',
                                        'SIN VERGUENZA',
                                        'RESTAURANTE',
                                        'PIZZA STICK',
                                        'AVENC ESPLUGUES'
                                        ]})
categories.update({'super i menjar':['DIA',
                            'A LA CART',
                            'DGUSTA',
                            'SERVIFRUIT',
                            'CONDIS',
                            'CAPRABO',
                            'ALCAMPO',
                            'CARNISSERIA',
                            'CORTE INGLES',
                            'EL CELLER',
                            'ALDI',
                            'LA SIRENA',
                            'MERCADONA',
                            'FRUITES I VERDURES',
                            'CA LA REMEI ESPL',
                            'ALBERTMAT',
                            'ENRIC ECO',
                            'CAL JAUME BELLVER',
                            'CLAREL'
                            ]})
categories.update({'rebuts':['YELLOW ENERGY',
                            'VOLKSWAGEN',
                            'CULEBRAS',
                            'Seguro',
                            'AIGUES DE BARCELONA',
                            'COM PROP CL LA VINYA',
                            'BENS IMMOBLES',
                            'AQUALOGY',
                            'NIMBONENS',
                            'RECIBO H.C.  Energia',
                            'EUROPOLIS',
                            'LLAR INFANS NIMBO',
                            'AXA GLOBAL',
                            'Cargo prima seguro',
                            'Recibo OALGT',
                            'Recibo NATIONALE NEDERLANDEN GENERALES'
                            ]})
categories.update({'panaderies':['TINYOL',
                                'BOULANGERIE',
                                'CLARITA',
                                'CIABBATTA',
                                'FIGULS',
                                'LA REPOSADA',
                                ]})
categories.update({'menjar plus':['GRANER DE LA SUSI',
                            'VERITAS',
                            'CENTRE DIETETIC CASELLAS',
                            'CELLER TORRAS',
                            ]})
categories.update({'extras varis':['DEL RETAL',
                            'CUCA DE LLUM',
                            'Photobox',
                            'TEATRES',
                            'ABACUS',
                            'TOUS',
                            'DECIMAS',
                            'DUET',
                            'DRIM',
                            'REDBUBBLE',
                            'DECATHLON',
                            'PARTY FIESTA',
                            'ARTESANS DE LABEL',
                            'HAIKU BARCELONA',
                            'BAZAR ORIENTAL ESPL',
                            'RUIXIANG 2013',
                            'JUGUETERIA MAINADA',
                            'XIAO FENG 2017',
                            'Pago S.E.DE CORREOS',
                            'TICKETEA MADRID',
                            'JOYERIA',
                            'SALTIMBANQUI',
                            'RESIN',
                            'SOULD PARK',
                            'TICKETMASTER',
                            'BUMBUETA',
                            'TABACS',
                            'SHOPDISNEY'
                            ]})
categories.update({'cotxe':['ES LA SARDANA',
                            'ZONA BLAVA ESTACIONAMENT',
                            'PARKING',
                            'Pago en AP.',
                            'SERVEI CATALA DE TRANSIT',
                            'GRUES BCN',
                            'A.C.E.S.A',
                            'CEDIPSA',
                            'INVICAT',
                            'GASAOLINERA',
                            'PARK.MARQUES',
                            'TUNELS CADI',
                            'ON APARCAR',
                            'ANEU OIL',
                            'AUCAT BAR VALLCARCA',
                            'AUCAT BAR CUBELLES'
                            ]})
categories.update({'fungibles':['FARMACIA',
                            'AUBERT',
                            'FACIL MOBEL',
                            'ENTRECORTINES',
                            'ELECTRILAMP',
                            'FERRETERIA MUSTE',
                            'IKEA',
                            'JUAN RODRIGUEZ CORNELLA',
                            'CORREOS Y TELEGRAF',
                            'YOIGO'
                            ]})
categories.update({'reintegraments':['Cargo cajero',
                            'Reintegro Cajero',
                            'Reintegro efectivo tarjeta'
                            ]})

